### ISSUE TITLE
Merge Sort Algorithm 

### ISSUE THREAD

**Issue by trishit78** [PrakashGatiyala/60-seconds-of-cpp#16]
Hey, I want to contribute this for Hacktoberfest 2022. please assign this to me @PrakashGatiyala.

**Comment by harshraj438524** [comment]
i would love to solve this problem ...will you provide this to me?

**Comment by trishit78** [comment]
Sorry to inform you that this issue is closed. You can read the  [https://github.com/PrakashGatiyala/60-seconds-of-cpp#readme](URL)  file to contribute to this project.
Thank you.
