### ISSUE TITLE
User Input Name in Cpp

### ISSUE THREAD

**Issue by Rimjhim20** [PrakashGatiyala/60-seconds-of-cpp#19]
Hii! Can you please assign me with this issue for hactoberfest. @PrakashGatiyala

**Comment by PrakashGatiyala** [comment]
> Hii! Can you please assign me with this issue for hactoberfest. @PrakashGatiyala

Sure, All the best.

**Comment by Abhinav-J05** [comment]
Hey! I would like to contribute in this, Please assign this to me.

**Comment by PrakashGatiyala** [comment]
> Hey! I would like to contribute in this, Please assign this to me.

I can't add duplicate snippets. Create new issue for none existing topic in my repo.

**Comment by PrakashGatiyala** [comment]
PR merged.
