### ISSUE TITLE
Map in C++ Standard Template Library (STL)

### ISSUE THREAD

**Issue by PrakashGatiyala** [PrakashGatiyala/60-seconds-of-cpp#25]
Maps are[ associative containers ](https://www.geeksforgeeks.org/containers-cpp-stl/)that store elements in a mapped fashion. Each element has a key value and a mapped value. No two mapped values can have the same key values.

**Comment by harsitagarwalla187** [comment]
Hi! Can i work in this issue?

**Comment by PrakashGatiyala** [comment]
> Hi! Can i work in this issue?

Create a new issue for another topic.

**Comment by PrakashGatiyala** [comment]
PR Merged.
