### ISSUE TITLE
Calculating XOR of all the elements in an array

### ISSUE THREAD

**Issue by taanii** [PrakashGatiyala/60-seconds-of-cpp#3]

**Comment by taanii** [comment]
Can I contribute to this issue? @PrakashGatiyala

**Comment by PrakashGatiyala** [comment]
> Can I contribute to this issue? @PrakashGatiyala

Sure

**Comment by PrakashGatiyala** [comment]
PR Merged. Closing the Issue. Thanks for contribution @taanii
