### ISSUE TITLE
Display all Factors of a Number

### ISSUE THREAD

**Issue by Rimjhim20** [PrakashGatiyala/60-seconds-of-cpp#45]
Assign me with this issue for hacktoberfest @PrakashGatiyala

**Comment by PrakashGatiyala** [comment]
> Assign me with this issue for hacktoberfest @PrakashGatiyala

sure

**Comment by Areedeep** [comment]
I request you to assign me this issue @PrakashGatiyala

**Comment by geoffgeorgein** [comment]
I can work on this. Please assign  me.

**Comment by PrakashGatiyala** [comment]
PR merged.
