### ISSUE TITLE
Request for putting Hacktoberfest label

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [PrakashGatiyala/60-seconds-of-cpp#5]
#### Hello @PrakashGatiyala
I request you to put the Hacktoberfest label on the repo so that me and other people can contribute to the repo during Hacktoberfest 2022.

Thank-you, you can close this issue after labeling

**Comment by PrakashGatiyala** [comment]
Thanks for suggestion @MrKrishnaAgarwal 
Done
![image](https://user-images.githubusercontent.com/34413515/192319227-e34a040f-eebb-43f7-9be0-969ba9e1d69f.png)

**Comment by MrKrishnaAgarwal** [comment]
Thanks
