### ISSUE TITLE
C++ Passing Array to Function

### ISSUE THREAD

**Issue by kuraakhilesh8230** [PrakashGatiyala/60-seconds-of-cpp#52]
Hello can you assign me this @PrakashGatiyala

**Comment by Areedeep** [comment]
Heello I request you to assign me this @PrakashGatiyala

**Comment by ansharora28** [comment]
@kuraakhilesh8230 are you working on this?
@PrakashGatiyala please assign it to me if that's okay :)

**Comment by PrakashGatiyala** [comment]
PR merged
