### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Kaushik-Iyer** [PrakashGatiyala/60-seconds-of-cpp#70]
The last line of README has a typo I guess. I'm submitting a pull request to change it, hopefully this issue falls under hacktoberfest :)

**Comment by Kaushik-Iyer** [comment]
#71

**Comment by PrakashGatiyala** [comment]
> The last line of README has a typo I guess. I'm submitting a pull request to change it, hopefully this issue falls under hacktoberfest :)

verify with hactoberfest dashboard.

**Comment by Kaushik-Iyer** [comment]
It wasnt updated :( did you add the hacktoberfest label to this issue?

**Comment by Kaushik-Iyer** [comment]
yeah I got a mail saying my request got approved by the project maintainer, thanks :)
