### ISSUE TITLE
Selection sort Algorithm

### ISSUE THREAD

**Issue by rithwik003** [PrakashGatiyala/60-seconds-of-cpp#8]
Hey, I want to contribute this for Hacktoberfest 2022. please assign this to me @PrakashGatiyala .

**Comment by PrakashGatiyala** [comment]
> Hey, I want to contribute this for Hacktoberfest 2022. please assign this to me @PrakashGatiyala .
Sure

**Comment by rithwik003** [comment]
Thank you @PrakashGatiyala

**Comment by ShishuSidharth** [comment]
What exactly do you want? Like code or just the algorithm?

**Comment by rithwik003** [comment]
code

**Comment by gautamV19** [comment]
Hey, I want to contribute this for Hacktoberfest 2022. please assign this to me @PrakashGatiyala
