### ISSUE TITLE
60-seconds-of-ts

### ISSUE THREAD

**Issue by slim-codes** [PrakashGatiyala/60-seconds-of-cpp#9]
I am a JavaScript developer and I would love to get involved in this project by implementing the same cpp algorithms here in another repo titled **60-seconds-of-ts** which would belong to @PrakashGatiyala  of course. I suggest **`60-seconds-of-ts`** instead of **`js`** since **`ts`** is strongly typed like `**cpp**`. Moreover, `ts `code can always be converted to vanilla `js `with ease if the need arises.

What are your thoughts?

**Comment by PrakashGatiyala** [comment]
> I am a JavaScript developer and I would love to get involved in this project by implementing the same cpp algorithms here in another repo titled **60-seconds-of-ts** which would belong to @PrakashGatiyala of course. I suggest **`60-seconds-of-ts`** instead of **`js`** since **`ts`** is strongly typed like `**cpp**`. Moreover, `ts `code can always be converted to vanilla `js `with ease if the need arises.
> 
> What are your thoughts?
I'm not sure. You can create it for yourself.
